package ${customPackage}.exception;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class ValidateRegisterException extends Exception {
    public ValidateRegisterException() {
    }

    public ValidateRegisterException(String message) {
        super(message);
    }

    public ValidateRegisterException(String message, Throwable cause) {
        super(message, cause);
    }
}
