package ${customPackage}.settings.bean;

import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
@TestConfiguration
public class AppConfigurationTest {
    public static final String BEAN_TEST = "stringTest";
    public static final String BEAN_TEST_DEFAULT_VALUE = "Bean Test AppConfigurationsTest";

    @Bean(BEAN_TEST)
    public String loadBeanTest() {
        return BEAN_TEST_DEFAULT_VALUE;
    }
}
