package ${customPackage}.controller;

import ${customPackage}.domain.SampleDomain;
import ${customPackage}.dto.InputDTO;
import ${customPackage}.dto.OutputDTO;
import ${customPackage}.exception.RegisterException;
import ${customPackage}.exception.ValidateRegisterException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
@RestController
public class SampleController {

    static final String HOME_MESSAGE = "Hello World";
    // Controllers must have only domain; never model/service
    private final SampleDomain sampleDomain;

    @Autowired
    public SampleController(SampleDomain sampleDomain) {
        this.sampleDomain = sampleDomain;
    }

    @GetMapping(produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity index() {
        return ResponseEntity.status(HttpStatus.OK).body(HOME_MESSAGE);
    }

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    public OutputDTO postSample(@RequestBody InputDTO inputDTO) throws RegisterException, ValidateRegisterException {
        return sampleDomain.process(inputDTO);
    }

}