package ${customPackage}.model.repository;

import ${customPackage}.exception.RegisterException;
import ${customPackage}.model.dao.SampleDAO;
import ${customPackage}.model.entity.SampleEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
@Repository
public class SampleRepository {

    /**
     * TODO - optional another source of data; ex:
     * private final SampleRestAPI sampleRestAPI;
     */
    private final SampleDAO sampleDAO;

    @Autowired
    public SampleRepository(SampleDAO sampleDAO) {
        this.sampleDAO = sampleDAO;
    }

    public SampleEntity register(SampleEntity entity) throws RegisterException {
        try {
            //Here you can put your sources and rules of data registration
            return registerInSampleDAO(entity);
        } catch (Exception e) {
            throw new RegisterException(e);
        }
    }

    private SampleEntity registerInSampleDAO(SampleEntity entity) throws Exception {
        int id = this.sampleDAO.insert(entity);
        entity.setId(id);
        return entity;
    }

    public SampleEntity getSampleEntityForName(String name) {
        //Here you can put your sources and rules of data registration
        return this.sampleDAO.select(name);
    }
}
