package ${customPackage}.model.dao;

import ${customPackage}.model.DatabaseMySQL;
import ${customPackage}.model.entity.SampleEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import static ${customPackage}.util.BeanConst.BEAN_SYSTEM_DATABASE;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
@Component
public class SampleDAO {

    private static final String SQL_INSERT = "INSERT INTO sample_tbl(name,age) VALUES(?,?)";

    private final DatabaseMySQL database;

    @Autowired
    public SampleDAO(@Qualifier(BEAN_SYSTEM_DATABASE) DatabaseMySQL database) {
        this.database = database;
    }

    public int insert(SampleEntity entity) throws Exception {
        try (PreparedStatement preparedStatement = database.getConnection().prepareStatement(SQL_INSERT)) {
            preparedStatement.setString(1, entity.getName());
            preparedStatement.setInt(2, entity.getAge());
            return preparedStatement.executeUpdate();
        }
    }

    private long getGeneratedKey(PreparedStatement preparedStatement) throws SQLException {
        try (ResultSet resultSet = preparedStatement.getGeneratedKeys()) {
            if (resultSet.next()) return resultSet.getLong(1);
        }
        return -1;
    }

    public SampleEntity select(String name) {
        //TODO
        return new SampleEntity(1, name, 10);
    }

}
