package ${customPackage};

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
@SpringBootTest
class ApplicationTest {

    @Test
    void contextLoads() {
        Assertions.assertTrue(true);
    }

}
