package ${customPackage}.dto;

import ${customPackage}.model.entity.SampleEntity;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
class InputDTOTest {
    @Test
    void convert_to_sample_entity() {
        InputDTO inputDTO = new InputDTO("name", 1);
        SampleEntity sampleEntity = InputDTO.toSampleEntity(inputDTO);
        Assertions.assertEquals(sampleEntity.getName(), inputDTO.getName());
        Assertions.assertEquals(sampleEntity.getAge(), inputDTO.getAge());
    }
}
