package ${customPackage}.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class HttpResponseException {

    private Date timestamp;
    private String message;
    private List<String> fields = new ArrayList<>();

    public HttpResponseException(String message) {
        this.timestamp = new Date();
        this.message = message;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void addFieldError(String field) {
        fields.add(field);
    }

    public List<String> getFields() {
        return fields;
    }

    @Override
    public String toString() {
        return "HttpResponseException{" +
                "timestamp=" + timestamp +
                ", message='" + message + '\'' +
                ", fields=" + fields +
                '}';
    }
}
