package ${customPackage}.dto;

import ${customPackage}.model.entity.SampleEntity;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class OutputDTO {

    public static OutputDTO fromSampleEntity(SampleEntity sampleEntity) {
        return new OutputDTO(sampleEntity.getId());
    }

    private int id;

    public OutputDTO() {
    }

    public OutputDTO(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return "OutputDTO{" +
                "id=" + id +
                '}';
    }
}
