package ${customPackage}.model.entity;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class SampleEntity {
    private int id;
    private String name;
    private int age;

    public SampleEntity(String name, int age) {
        this(0, name, age);
    }

    public SampleEntity(int id, String name, int age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }


    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return "SampleEntity{" +
                "name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}
