package ${customPackage}.util;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class ApplicationConst {
    public static final String PROFILE_TEST = "test";
    public static final String KEY_APPLICATION_VERSION = "${application.version}";
    public static final String KEY_SYSTEM_PROPERTIES_PATH = "${system.properties.path}";
}