package ${customPackage}.util;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class BeanConst {
    public static final String BEAN_SYSTEM_PROPERTIES = "systemProperties";
    public static final String BEAN_SYSTEM_DATABASE = "systemDatabase";
}