package ${customPackage}.util;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
public class SystemPropertiesConst {

    public static final String SPRING_PROFILES_ACTIVE = "spring.profiles.active";

    public static final String SYSTEM_DATABASE_URL = "system.database.url";
    public static final String SYSTEM_DATABASE_USER = "system.database.user";
    public static final String SYSTEM_DATABASE_PASSWORD = "system.database.password";

}
